use sakila;
select first_name, last_name from actor;
select concat(first_name, " ", last_name) as 'Name' from actor;
select actor_id, first_name, last_name from actor where first_name="JOE";
select * from actor where last_name like "%GEN%";
select * from actor where last_name like "%LI%" order by last_name, first_name;
select country_id, country from country where country in ("Afghanistan", "Bangladesh", "China");
alter table actor add description blob;
alter table actor drop description;
select last_name, count(last_name) as 'Count' from actor group by last_name;
select last_name, count(last_name) as 'Count' from actor group by last_name having count(last_name)>1;
update actor set first_name="HARPO" where first_name="GROUCHO" and last_name="WILLIAMS";
update actor set first_name="GROUCHO" where first_name="HARPO";
show create table address;
select first_name, last_name, address from staff inner join address using (address_id);
select first_name, last_name, sum(amount) from staff join payment using (staff_id) where payment_date like "2005-08%" group by staff_id;
select title, count(actor_id) as 'Actors' from film join film_actor on film.film_id=film_actor.film_id group by film.film_id;
select count(inventory_id) as 'Copies of Hunchback' from inventory where film_id = (select film_id from film where title = "Hunchback Impossible");
select first_name,last_name,sum(amount) as 'Total' from customer join payment on customer.customer_id=payment.customer_id group by customer.customer_id order by last_name;
select title, language_id from film where title like "K%" or title like "Q%"  and language_id=(select language_id from language where name="English");
select first_name, last_name from actor where actor_id in (select actor_id from film_actor where film_id = (select film_id from film where title = "Alone Trip"));
select first_name, last_name, email from customer join address using (address_id) join city using (city_id) join country using (country_id) where country = "Canada";
select title from film where film_id in (select film_id from film_category where category_id=(select category_id from category where name="Family"));
select title, count(rental_id) as 'Count' from film join inventory on film.film_id=inventory.film_id join rental on inventory.inventory_id=rental.inventory_id group by film.film_id order by count(rental_id) desc;
select store_id, sum(amount) from payment join staff using (staff_id) group by store_id;
select store_id, city, country from store join address on store.address_id=address.address_id join city on address.city_id=city.city_id join country on city.country_id=country.country_id; 
select category.name, sum(amount) from category join film_category using (category_id) join inventory using (film_id) join rental using (inventory_id) join payment using (rental_id) group by name order by sum(amount) desc limit 5;
create view top_grossing_genres as
select name, sum(amount) from category join film_category using (category_id) join inventory using (film_id) join rental using (inventory_id) join payment using (rental_id) group by name order by sum(amount) desc limit 5;
select * from top_grossing_genres;